#!/usr/bin/env python3
"""Compare AGNOS kernels with bounded build identity at matching locations."""
import argparse
from pathlib import Path
import re
import struct
import sys
import zlib

FDT = b"\xd0\x0d\xfe\xed"
BUILD_ID = b"\x04\x00\x00\x00\x14\x00\x00\x00\x03\x00\x00\x00GNU\x00"
CERT_MARKER = b"Build time autogenerated kernel key"
SAE_MARKERS = (
  b"set authentication type to SAE",
  b"Roaming not supported for SAE connection",
  b"SAE: sent cmd",
  b"Received SAE Auth frame",
)
MAX_INFLATED = 64 * 1024 * 1024


def split(boot):
  """Return (Android v0 header without id, Image, exact appended FDT chain)."""
  if len(boot) < 1632 or boot[:8] != b"ANDROID!":
    raise ValueError("invalid or truncated Android boot header")
  ksize, _, rsize, _, ssize, _, _, page, version, _ = struct.unpack_from("<10I", boot, 8)
  if version != 0 or rsize or ssize:
    raise ValueError("unsupported boot layout: expected Android v0 with no external ramdisk/second stage")
  if page < 1632 or page & (page - 1) or not ksize or page + ksize > len(boot):
    raise ValueError("invalid page size or truncated kernel")
  if (page + ksize + page - 1) // page * page > len(boot):
    raise ValueError("truncated boot page")
  header = boot[:576] + boot[608:1632]
  kernel = boot[page:page + ksize]
  # A magic match alone is insufficient: every totalsize must advance within the
  # tail, and the last DTB must end exactly at kernel_size (not file padding).
  for match in re.finditer(re.escape(FDT), kernel):
    offset = match.start()
    if offset % 4:
      continue
    pos = offset
    while pos + 40 <= len(kernel) and kernel[pos:pos + 4] == FDT:
      size = struct.unpack_from(">I", kernel, pos + 4)[0]
      if size < 40 or size > len(kernel) - pos:
        break
      pos += size
    if pos == len(kernel):
      return header, kernel[:offset], kernel[offset:]
  raise ValueError("no valid appended DTB chain covering the kernel tail")


def gunzip_member(data):
  decoder = zlib.decompressobj(16 + zlib.MAX_WBITS)
  raw = decoder.decompress(data, MAX_INFLATED + 1)
  if len(raw) > MAX_INFLATED or not decoder.eof:
    raise ValueError("truncated gzip member or inflated size exceeds cap")
  return len(data) - len(decoder.unused_data), raw


def ikconfig(img):
  markers = [m.start() for m in re.finditer(b"IKCFG_ST", img)]
  if len(markers) != 1:
    raise ValueError("expected exactly one embedded ikconfig")
  offset = markers[0] + 8
  size, raw = gunzip_member(img[offset:])
  if img[offset + size:offset + size + 8] != b"IKCFG_ED":
    raise ValueError("invalid ikconfig end marker")
  return raw


def cstr_spans(img, prefix):
  spans = []
  for match in re.finditer(re.escape(prefix), img):
    end = match.start()
    limit = min(len(img), match.start() + 256)
    while end < limit and img[end] not in (0, 10):
      end += 1
    if end == limit:
      raise ValueError(f"unterminated or overlong build string {prefix!r} (limit 256 bytes)")
    spans.append((match.start(), end + 1))
  return spans


def buildid_spans(img):
  spans = [(m.end(), m.end() + 20) for m in re.finditer(re.escape(BUILD_ID), img)]
  if any(end > len(img) for _, end in spans):
    raise ValueError("truncated GNU build-id")
  return spans


def der_field(img, start, limit):
  """Read a definite, minimally encoded DER tag/length within its parent."""
  if start + 2 > limit:
    raise ValueError("truncated DER field")
  tag, size = img[start:start + 2]
  content = start + 2
  if size & 0x80:
    count = size & 0x7f
    if not 1 <= count <= 4 or content + count > limit or img[content] == 0:
      raise ValueError("invalid DER length")
    size = int.from_bytes(img[content:content + count], "big")
    if size < 128:
      raise ValueError("nonminimal DER length")
    content += count
  if content + size > limit:
    raise ValueError("DER field exceeds parent")
  return tag, content, content + size


def certificate_end(img, start, marker):
  if img[start:start + 2] != b"\x30\x82":
    raise ValueError("not a Certificate sequence")
  _, content, end = der_field(img, start, min(len(img), start + 4096))
  # Certificate ::= SEQUENCE { tbsCertificate SEQUENCE,
  #                            signatureAlgorithm SEQUENCE, signatureValue BIT STRING }
  tag, tbs, next_field = der_field(img, content, end)
  if tag != 0x30 or not tbs <= marker.start() < marker.end() <= next_field:
    raise ValueError("key marker is outside tbsCertificate")
  tag, _, next_field = der_field(img, next_field, end)
  if tag != 0x30:
    raise ValueError("invalid signatureAlgorithm")
  tag, bits, final = der_field(img, next_field, end)
  if tag != 0x03 or final != end or bits >= final or img[bits] > 7:
    raise ValueError("invalid signatureValue or trailing Certificate data")
  if img[bits] and (bits + 1 == final or img[final - 1] & ((1 << img[bits]) - 1)):
    raise ValueError("invalid BIT STRING padding")
  return end


def cert_spans(img):
  spans = set()
  for match in re.finditer(CERT_MARKER, img):
    # Nearest valid Certificate, not an arbitrary enclosing SEQUENCE or address.
    for start in range(match.start(), max(-1, match.end() - 4097), -1):
      if img[start:start + 2] != b"\x30\x82":
        continue
      try:
        end = certificate_end(img, start, match)
      except ValueError:
        continue
      spans.add((start, end))
      break
    else:
      raise ValueError("no bounded X.509 Certificate enclosing autogenerated key marker")
  return sorted(spans)


def initramfs_members(img):
  members = []
  for match in re.finditer(b"\x1f\x8b\x08", img):
    try:
      size, raw = gunzip_member(img[match.start():match.start() + 65536])
    except (ValueError, zlib.error):
      # Other data can contain gzip magic. A missing/malformed cpio member is
      # rejected below; ikconfig is independently decoded and checked above.
      continue
    if raw.startswith(b"070701"):
      if ((match.start() + size + 3) & ~3) + 8 > len(img):
        raise ValueError("truncated initramfs size span")
      members.append((match.start(), size, raw))
  if not members:
    raise ValueError("built-in initramfs not found or malformed")
  return members


def initramfs(img):
  members = initramfs_members(img)
  if len(members) != 1:
    raise ValueError("expected exactly one built-in initramfs")
  return members[0]


def cpio_norm(raw):
  """Validate newc bounds and normalize only c_mtime; retain all other bytes."""
  normalized = bytearray(raw)
  pos = 0
  while True:
    if pos + 110 > len(raw) or raw[pos:pos + 6] != b"070701":
      raise ValueError("invalid or truncated newc cpio header")
    fields = raw[pos + 6:pos + 110]
    if not re.fullmatch(b"[0-9a-fA-F]{104}", fields):
      raise ValueError("invalid newc cpio fields")
    namesize = int(raw[pos + 94:pos + 102], 16)
    filesize = int(raw[pos + 54:pos + 62], 16)
    name_end = pos + 110 + namesize
    data_start = (name_end + 3) & ~3
    end = (data_start + filesize + 3) & ~3
    if not namesize or end > len(raw) or raw[name_end - 1] != 0:
      raise ValueError("invalid or truncated newc cpio entry")
    normalized[pos + 46:pos + 54] = b"0" * 8
    if raw[pos + 110:name_end - 1] == b"TRAILER!!!":
      if filesize:
        raise ValueError("nonempty newc cpio trailer")
      return bytes(normalized)
    pos = end


def _equivalent(base, new):
  reasons = []
  header_a, image_a, dtb_a = split(base)
  header_b, image_b, dtb_b = split(new)
  if header_a != header_b:
    reasons.append("boot header (incl. cmdline) differs")
  if dtb_a != dtb_b:
    reasons.append("appended DTB differs")
  if len(image_a) != len(image_b):
    return False, reasons + ["kernel Image size differs"]
  if ikconfig(image_a) != ikconfig(image_b):
    reasons.append("kernel config differs")
  identities = []
  ramdisks = []
  for img in (image_a, image_b):
    ramdisks.append(initramfs_members(img))
    identities.append({
      "banner": cstr_spans(img, b"Linux version "),
      "uts": cstr_spans(img, b"#1 SMP PREEMPT "),
      "build-id": buildid_spans(img),
      "cert": cert_spans(img),
      "initramfs": [(offset, offset + size) for offset, size, _ in ramdisks[-1]],
    })
  spans = []
  for kind, spans_a in identities[0].items():
    spans_b = identities[1][kind]
    if [start for start, _ in spans_a] != [start for start, _ in spans_b]:
      reasons.append(f"{kind} identity span starts differ")
      continue
    if kind == "cert" and spans_a != spans_b:
      reasons.append("cert identity span ends differ")
      continue
    for (start, end_a), (_, end_b) in zip(spans_a, spans_b):
      if kind in ("banner", "uts"):
        short, lo, hi = (image_a, end_a, end_b) if end_a <= end_b else (image_b, end_b, end_a)
        if hi - lo > 16 or image_a[end_a - 1] != image_b[end_b - 1] or any(short[lo:hi]):
          reasons.append(f"{kind} identity span length/terminator changed")
          continue
      if kind == "initramfs":
        continue
      spans.append((start, max(end_a, end_b)))
  # A new marker cannot authorize a new mask, even if its payload looks valid.
  if reasons:
    return False, reasons
  pointers = []
  for (offset, size_a, raw_a), (_, size_b, raw_b) in zip(*ramdisks):
    if cpio_norm(raw_a) != cpio_norm(raw_b):
      reasons.append("initramfs content differs")
    if abs(size_a - size_b) > 16:
      reasons.append("initramfs compressed length delta too large")
    if ((offset + size_a + 3) & ~3) != ((offset + size_b + 3) & ~3):
      reasons.append("__initramfs_size word moved")
    if any(img[offset + 3] & ~0x08 for img in (image_a, image_b)):
      reasons.append("initramfs gzip flags the kernel cannot parse")
    for img, size in ((image_a, size_a), (image_b, size_b)):
      word = (offset + size + 3) & ~3
      if struct.unpack_from("<Q", img, word)[0] != size or any(img[offset + size:word]):
        reasons.append("__initramfs_size word or alignment padding invalid")
      spans.append((word, word + 8))
    spans.append((offset, offset + max(size_a, size_b)))
    pointers.append((offset + size_a, size_a - size_b))

  bad = []
  runs = 0
  pointer_word = None
  pos = 0
  while pos < len(image_a):
    if image_a[pos] == image_b[pos]:
      pos += 1
      continue
    start = pos
    while pos < len(image_a) and image_a[pos] != image_b[pos]:
      pos += 1
    runs += 1
    if any(a <= start and pos <= b for a, b in spans):
      continue
    # A 32-bit symbol word just after initramfs moves with its compressed length.
    # Keep the prototype's +/-64 bound and exact delta, never mask its neighbors.
    word = start & ~3
    if pointer_word in (None, word) and pos <= word + 4 and word + 4 <= len(image_a):
      value_a = struct.unpack_from("<I", image_a, word)[0]
      value_b = struct.unpack_from("<I", image_b, word)[0]
      if any(value_a - value_b == delta and abs(value_a - end) <= 64 for end, delta in pointers):
        pointer_word = word
        continue
    bad.append((start, pos))
  if bad:
    reasons.append(f"{len(bad)} kernel Image byte runs differ outside build identity (first at {bad[0][0]:#x})")
  return not reasons, reasons or [f"{runs} differing runs, all build identity"]


def equivalent(base_bytes, new_bytes):
  """Fail closed on any malformed structure or decompression/parse exception."""
  try:
    return _equivalent(base_bytes, new_bytes)
  except Exception as error:
    return False, [f"boot parse failed: {type(error).__name__}: {error}"]


def native_sae(boot_bytes):
  _, img, _ = split(boot_bytes)
  counts = {marker.decode(): img.count(marker) for marker in SAE_MARKERS}
  state = "all" if all(counts.values()) else "partial" if any(counts.values()) else "none"
  return state, counts


def main():
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("base", type=Path)
  parser.add_argument("new", type=Path)
  args = parser.parse_args()
  try:
    ok, reasons = equivalent(args.base.read_bytes(), args.new.read_bytes())
  except OSError as error:
    ok, reasons = False, [str(error)]
  print(f"{'EQUIVALENT' if ok else 'DIFFERENT'}: {'; '.join(reasons)}")
  return 0 if ok else 1


if __name__ == "__main__":
  sys.exit(main())
