#!/usr/bin/env python3
"""Verify an Android sparse system image and inspect ext4 with read-only debugfs."""
import argparse
import gzip
import hashlib
import json
import lzma
import os
from pathlib import Path
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import urllib.request
import zlib

BLOCK = 1024 * 1024
MAX_RAW = 16 * 1024**3


def require(ok, message):
  if not ok:
    raise ValueError(message)


def sha_file(path):
  with open(path, 'rb') as stream:
    return hashlib.file_digest(stream, 'sha256').hexdigest()


def exact(stream, size):
  data = stream.read(size)
  require(len(data) == size, 'truncated sparse image')
  return data


class HashReader:
  def __init__(self, stream):
    self.stream, self.digest = stream, hashlib.sha256()

  def read(self, size):
    data = self.stream.read(size)
    self.digest.update(data)
    return data


def expand(stream, output):
  """Hash all sparse bytes and expanded bytes; DONT_CARE is deterministic zero."""
  source = HashReader(stream)
  magic, major, minor, fh, ch, block, blocks, chunks, checksum = struct.unpack('<I4H4I', exact(source, 28))
  require(magic == 0xed26ff3a and major == 1 and minor == 0, 'unsupported sparse header')
  require(28 <= fh <= 4096 and 12 <= ch <= 4096, 'bad sparse header length')
  require(0 < block <= BLOCK and block % 4 == 0 and 0 < blocks * block <= MAX_RAW,
          'invalid sparse block size/count')
  require(0 < chunks <= 1000000, 'invalid sparse chunk count')
  exact(source, fh - 28)
  digest, crc, written = hashlib.sha256(), 0, 0
  for _ in range(chunks):
    kind, reserved, count, length = struct.unpack('<2H2I', exact(source, 12))
    exact(source, ch - 12)
    size = count * block
    require(written + size <= blocks * block, 'sparse chunk exceeds total length')
    payload = {0xcac1: size, 0xcac2: 4, 0xcac3: 0, 0xcac4: 4}.get(kind)
    require(payload is not None and length == ch + payload, 'bad sparse chunk length/type')
    if kind == 0xcac4:
      require(count == 0, 'CRC chunk has output blocks')
      require(struct.unpack('<I', exact(source, 4))[0] == crc, 'bad sparse CRC')
      continue
    fill = exact(source, 4) if kind == 0xcac2 else b'\0' * 4
    remaining = size
    while remaining:
      n = min(BLOCK, remaining)
      data = exact(source, n) if kind == 0xcac1 else fill * (n // 4)
      digest.update(data)
      crc = zlib.crc32(data, crc)
      if kind == 0xcac3:
        output.seek(n, os.SEEK_CUR)
      else:
        output.write(data)
      remaining -= n
    written += size
  require(written == blocks * block and not source.read(1), 'bad sparse total length/trailing bytes')
  require(checksum == 0 or checksum == crc, 'bad sparse header CRC')
  output.truncate(written)
  return source.digest.hexdigest(), digest.hexdigest()


def debugfs_path():
  return shutil.which('debugfs') or '/opt/homebrew/opt/e2fsprogs/sbin/debugfs'


def inspect(raw, directory, debugfs=None):
  def debug(command, allow_missing=False):
    # Never -w, never a mount. debugfs can return 0 for filesystem errors.
    result = subprocess.run([debugfs or debugfs_path(), '-R', command, str(raw)],
                            capture_output=True, text=True, check=True)
    if allow_missing and 'File not found' in result.stderr:
      return ''
    require(not re.search(r'(not found|short read|bad magic|Filesystem not open)', result.stderr, re.I),
            'debugfs: ' + result.stderr.strip())
    return result.stdout

  def dump(source, name, maximum):
    stat = debug('stat ' + source)
    size = re.search(r'\bSize:\s+(\d+)', stat)
    require(size and 0 < int(size[1]) <= maximum and 'Type: regular' in stat, 'invalid inode: ' + source)
    target = directory / name
    # Paths generated by tempfile, quoted for debugfs's own parser.
    require('"' not in str(target) and '\n' not in str(target), 'unsafe output path')
    debug(f'dump {source} "{target}"')
    require(target.is_file() and target.stat().st_size == int(size[1]), 'debugfs dump failed')
    return target.read_bytes()

  binary = dump('/usr/sbin/wpa_supplicant', 'stock-wpa_supplicant', 32 * BLOCK)
  status = dump('/usr/default/var/lib/dpkg/status', 'dpkg-status', 32 * BLOCK).decode()
  versions = [re.search(r'^Version: (.+)$', stanza, re.M)[1] for stanza in status.split('\n\n')
              if re.search(r'^Package: wpasupplicant$', stanza, re.M)]
  require(len(versions) == 1, 'missing/ambiguous wpasupplicant dpkg stanza')
  changelog = dump('/usr/share/doc/wpasupplicant/changelog.Debian.gz', 'changelog.gz', 4 * BLOCK)
  head = gzip.decompress(changelog).decode().splitlines()[0]
  require(head.startswith(f'wpa ({versions[0]}) '), 'dpkg/changelog version mismatch')
  listing = debug('ls -p /lib/modules', allow_missing=True)
  modules = False
  for line in listing.splitlines():
    fields = line.split('/')
    if len(fields) > 5 and re.fullmatch(r'4\.9\.[A-Za-z0-9_.+-]+', fields[5]):
      children = debug('ls -p /lib/modules/' + fields[5])
      modules |= any(len(row.split('/')) > 5 and row.split('/')[5] not in ('.', '..', '')
                     for row in children.splitlines())
  return {'stock_wpa_sha256': hashlib.sha256(binary).hexdigest(), 'dpkg_version': versions[0],
          'changelog_head': head, 'kernel_modules_present': modules, 'probed_by': 'system_probe.py v1'}


def probe(stream, expect_hash, expect_raw, *, keep=None, debugfs=None):
  for value in (expect_hash, expect_raw):
    require(re.fullmatch('[0-9a-f]{64}', value), 'invalid expected hash')
  if keep:
    require(not keep.exists(), 'probe destination already exists')
    keep.parent.mkdir(parents=True, exist_ok=True)
  with tempfile.TemporaryDirectory(prefix='wpa-probe-', dir=keep.parent if keep else None) as temporary:
    work = Path(temporary)
    raw = work / 'system.raw'
    with raw.open('w+b') as out:
      sparse_hash, raw_hash = expand(stream, out)
    require(sparse_hash == expect_hash, 'sparse hash mismatch; discarding probe')
    require(raw_hash == expect_raw, 'raw hash mismatch; discarding probe')
    result = inspect(raw, work, debugfs)
    result = {'hash': sparse_hash, 'hash_raw': raw_hash, **result}
    (work / 'probe.json').write_text(json.dumps(result, indent=2) + '\n')
    if keep:
      os.rename(work, keep)
    return result


def main():
  parser = argparse.ArgumentParser(description=__doc__)
  source = parser.add_mutually_exclusive_group(required=True)
  source.add_argument('--sparse', type=Path)
  source.add_argument('--url')
  parser.add_argument('--expect-hash', required=True)
  parser.add_argument('--expect-hash-raw', required=True)
  parser.add_argument('--out', type=Path, required=True)
  parser.add_argument('--keep', type=Path, help='retain verified raw image for T1')
  parser.add_argument('--debugfs', default=debugfs_path())
  args = parser.parse_args()
  try:
    if args.sparse:
      stream = args.sparse.open('rb')
    else:
      require(args.url.startswith('https://'), 'HTTPS required')
      stream = lzma.LZMAFile(urllib.request.urlopen(args.url, timeout=120))
    with stream:
      result = probe(stream, args.expect_hash, args.expect_hash_raw, keep=args.keep, debugfs=args.debugfs)
    args.out.write_text(json.dumps(result, indent=2) + '\n')
    print('PROBE: OK: ' + result['hash_raw'])
    return 0
  except Exception as error:
    args.out.unlink(missing_ok=True)
    print(f'PROBE: HOLD: {error}', file=sys.stderr)
    return 1


if __name__ == '__main__':
  sys.exit(main())
